typedef CountryCode = ({String code, String label});

const List<CountryCode> countryCodes = <CountryCode>[
  (code: '+93', label: 'Afghanistan'),
  (code: '+27', label: 'Afrique du Sud'),
  (code: '+355', label: 'Albanie'),
  (code: '+213', label: 'Algérie'),
  (code: '+49', label: 'Allemagne'),
  (code: '+376', label: 'Andorre'),
  (code: '+244', label: 'Angola'),
  (code: '+1', label: 'Antigua-et-Barbuda'),
  (code: '+966', label: 'Arabie saoudite'),
  (code: '+54', label: 'Argentine'),
  (code: '+374', label: 'Arménie'),
  (code: '+61', label: 'Australie'),
  (code: '+43', label: 'Autriche'),
  (code: '+994', label: 'Azerbaïdjan'),
  (code: '+1', label: 'Bahamas'),
  (code: '+973', label: 'Bahreïn'),
  (code: '+880', label: 'Bangladesh'),
  (code: '+1', label: 'Barbade'),
  (code: '+32', label: 'Belgique'),
  (code: '+501', label: 'Belize'),
  (code: '+229', label: 'Bénin'),
  (code: '+975', label: 'Bhoutan'),
  (code: '+375', label: 'Biélorussie'),
  (code: '+95', label: 'Birmanie (Myanmar)'),
  (code: '+591', label: 'Bolivie'),
  (code: '+387', label: 'Bosnie-Herzégovine'),
  (code: '+267', label: 'Botswana'),
  (code: '+55', label: 'Brésil'),
  (code: '+673', label: 'Brunei'),
  (code: '+359', label: 'Bulgarie'),
  (code: '+226', label: 'Burkina Faso'),
  (code: '+257', label: 'Burundi'),
  (code: '+855', label: 'Cambodge'),
  (code: '+237', label: 'Cameroun'),
  (code: '+1', label: 'Canada'),
  (code: '+238', label: 'Cap-Vert'),
  (code: '+236', label: 'République centrafricaine'),
  (code: '+56', label: 'Chili'),
  (code: '+86', label: 'Chine'),
  (code: '+357', label: 'Chypre'),
  (code: '+57', label: 'Colombie'),
  (code: '+269', label: 'Comores'),
  (code: '+242', label: 'République du Congo'),
  (code: '+243', label: 'République démocratique du Congo'),
  (code: '+82', label: 'Corée du Sud'),
  (code: '+850', label: 'Corée du Nord'),
  (code: '+506', label: 'Costa Rica'),
  (code: '+225', label: "Côte d'Ivoire"),
  (code: '+385', label: 'Croatie'),
  (code: '+53', label: 'Cuba'),
  (code: '+45', label: 'Danemark'),
  (code: '+253', label: 'Djibouti'),
  (code: '+1', label: 'Dominique'),
  (code: '+20', label: 'Égypte'),
  (code: '+971', label: 'Émirats arabes unis'),
  (code: '+593', label: 'Équateur'),
  (code: '+291', label: 'Érythrée'),
  (code: '+34', label: 'Espagne'),
  (code: '+372', label: 'Estonie'),
  (code: '+268', label: 'Eswatini'),
  (code: '+251', label: 'Éthiopie'),
  (code: '+679', label: 'Fidji'),
  (code: '+358', label: 'Finlande'),
  (code: '+33', label: 'France'),
  (code: '+241', label: 'Gabon'),
  (code: '+220', label: 'Gambie'),
  (code: '+995', label: 'Géorgie'),
  (code: '+233', label: 'Ghana'),
  (code: '+30', label: 'Grèce'),
  (code: '+1', label: 'Grenade'),
  (code: '+502', label: 'Guatemala'),
  (code: '+224', label: 'Guinée'),
  (code: '+245', label: 'Guinée-Bissau'),
  (code: '+240', label: 'Guinée équatoriale'),
  (code: '+592', label: 'Guyana'),
  (code: '+509', label: 'Haïti'),
  (code: '+504', label: 'Honduras'),
  (code: '+36', label: 'Hongrie'),
  (code: '+91', label: 'Inde'),
  (code: '+62', label: 'Indonésie'),
  (code: '+964', label: 'Irak'),
  (code: '+98', label: 'Iran'),
  (code: '+353', label: 'Irlande'),
  (code: '+354', label: 'Islande'),
  (code: '+972', label: 'Israël'),
  (code: '+39', label: 'Italie'),
  (code: '+1', label: 'Jamaïque'),
  (code: '+81', label: 'Japon'),
  (code: '+962', label: 'Jordanie'),
  (code: '+7', label: 'Kazakhstan'),
  (code: '+254', label: 'Kenya'),
  (code: '+996', label: 'Kirghizistan'),
  (code: '+686', label: 'Kiribati'),
  (code: '+383', label: 'Kosovo'),
  (code: '+965', label: 'Koweït'),
  (code: '+856', label: 'Laos'),
  (code: '+266', label: 'Lesotho'),
  (code: '+371', label: 'Lettonie'),
  (code: '+961', label: 'Liban'),
  (code: '+231', label: 'Libéria'),
  (code: '+218', label: 'Libye'),
  (code: '+423', label: 'Liechtenstein'),
  (code: '+370', label: 'Lituanie'),
  (code: '+352', label: 'Luxembourg'),
  (code: '+261', label: 'Madagascar'),
  (code: '+60', label: 'Malaisie'),
  (code: '+265', label: 'Malawi'),
  (code: '+960', label: 'Maldives'),
  (code: '+223', label: 'Mali'),
  (code: '+356', label: 'Malte'),
  (code: '+212', label: 'Maroc'),
  (code: '+692', label: 'Îles Marshall'),
  (code: '+230', label: 'Maurice'),
  (code: '+222', label: 'Mauritanie'),
  (code: '+52', label: 'Mexique'),
  (code: '+691', label: 'Micronésie'),
  (code: '+373', label: 'Moldavie'),
  (code: '+377', label: 'Monaco'),
  (code: '+976', label: 'Mongolie'),
  (code: '+382', label: 'Monténégro'),
  (code: '+258', label: 'Mozambique'),
  (code: '+264', label: 'Namibie'),
  (code: '+674', label: 'Nauru'),
  (code: '+977', label: 'Népal'),
  (code: '+505', label: 'Nicaragua'),
  (code: '+227', label: 'Niger'),
  (code: '+234', label: 'Nigeria'),
  (code: '+47', label: 'Norvège'),
  (code: '+64', label: 'Nouvelle-Zélande'),
  (code: '+968', label: 'Oman'),
  (code: '+256', label: 'Ouganda'),
  (code: '+998', label: 'Ouzbékistan'),
  (code: '+92', label: 'Pakistan'),
  (code: '+680', label: 'Palaos'),
  (code: '+970', label: 'Palestine'),
  (code: '+507', label: 'Panama'),
  (code: '+675', label: 'Papouasie-Nouvelle-Guinée'),
  (code: '+595', label: 'Paraguay'),
  (code: '+31', label: 'Pays-Bas'),
  (code: '+51', label: 'Pérou'),
  (code: '+63', label: 'Philippines'),
  (code: '+48', label: 'Pologne'),
  (code: '+351', label: 'Portugal'),
  (code: '+974', label: 'Qatar'),
  (code: '+40', label: 'Roumanie'),
  (code: '+44', label: 'Royaume-Uni'),
  (code: '+7', label: 'Russie'),
  (code: '+250', label: 'Rwanda'),
  (code: '+1', label: 'Saint-Kitts-et-Nevis'),
  (code: '+378', label: 'Saint-Marin'),
  (code: '+1', label: 'Saint-Vincent-et-les-Grenadines'),
  (code: '+1', label: 'Sainte-Lucie'),
  (code: '+503', label: 'Salvador'),
  (code: '+685', label: 'Samoa'),
  (code: '+239', label: 'Sao Tomé-et-Principe'),
  (code: '+221', label: 'Sénégal'),
  (code: '+381', label: 'Serbie'),
  (code: '+248', label: 'Seychelles'),
  (code: '+232', label: 'Sierra Leone'),
  (code: '+65', label: 'Singapour'),
  (code: '+421', label: 'Slovaquie'),
  (code: '+386', label: 'Slovénie'),
  (code: '+252', label: 'Somalie'),
  (code: '+249', label: 'Soudan'),
  (code: '+211', label: 'Soudan du Sud'),
  (code: '+94', label: 'Sri Lanka'),
  (code: '+46', label: 'Suède'),
  (code: '+41', label: 'Suisse'),
  (code: '+597', label: 'Suriname'),
  (code: '+963', label: 'Syrie'),
  (code: '+992', label: 'Tadjikistan'),
  (code: '+255', label: 'Tanzanie'),
  (code: '+235', label: 'Tchad'),
  (code: '+420', label: 'Tchéquie'),
  (code: '+66', label: 'Thaïlande'),
  (code: '+670', label: 'Timor oriental'),
  (code: '+228', label: 'Togo'),
  (code: '+676', label: 'Tonga'),
  (code: '+1', label: 'Trinité-et-Tobago'),
  (code: '+216', label: 'Tunisie'),
  (code: '+993', label: 'Turkménistan'),
  (code: '+90', label: 'Turquie'),
  (code: '+688', label: 'Tuvalu'),
  (code: '+380', label: 'Ukraine'),
  (code: '+598', label: 'Uruguay'),
  (code: '+678', label: 'Vanuatu'),
  (code: '+379', label: 'Vatican'),
  (code: '+58', label: 'Venezuela'),
  (code: '+84', label: 'Viêt Nam'),
  (code: '+967', label: 'Yémen'),
  (code: '+260', label: 'Zambie'),
  (code: '+263', label: 'Zimbabwe'),
];

CountryCode? countryCodeByDialCode(String code) {
  for (final CountryCode country in countryCodes) {
    if (country.code == code) {
      return country;
    }
  }
  return null;
}

final List<CountryCode> _countryCodesByCodeLength =
    List<CountryCode>.of(countryCodes)..sort((CountryCode a, CountryCode b) {
      final int byLength = b.code.length.compareTo(a.code.length);
      if (byLength != 0) {
        return byLength;
      }
      return b.code.compareTo(a.code);
    });

({String countryCode, String phone})? splitPhoneNumber(String raw) {
  for (final CountryCode country in _countryCodesByCodeLength) {
    if (raw.startsWith(country.code) && raw.length > country.code.length) {
      return (
        countryCode: country.code,
        phone: raw.substring(country.code.length),
      );
    }
  }
  return null;
}
