// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3HZyKNwd2ik12hC_RLuAUAEAaAb6g0R4',
    appId: '1:540209425492:web:766c175245f574fc7f51c1',
    messagingSenderId: '540209425492',
    projectId: 'kiosk-mind',
    authDomain: 'kiosk-mind.firebaseapp.com',
    storageBucket: 'kiosk-mind.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJhwOxIQYJm6MezDlOlwkQoFMtY69zI3E',
    appId: '1:540209425492:android:bac1944041dbf5ae7f51c1',
    messagingSenderId: '540209425492',
    projectId: 'kiosk-mind',
    storageBucket: 'kiosk-mind.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjTfAT8eCGECLUONjNTc56xT5yDMQC6SQ',
    appId: '1:540209425492:ios:4af95570ab19f4307f51c1',
    messagingSenderId: '540209425492',
    projectId: 'kiosk-mind',
    storageBucket: 'kiosk-mind.firebasestorage.app',
    iosBundleId: 'com.example.kioskMind',
  );
}
