/// How a command was produced. Stored as a code, never as localized text.
enum CommandSource {
  voice('VOICE'),
  manual('MANUAL');

  const CommandSource(this.code);

  final String code;
}

/// Context shared by every intent call: who asked, when, and under which
/// command identifier.
///
/// [commandId] is generated by the voice layer and becomes the document
/// identifier, which is what makes a replay detectable (contract A3).
/// [dateTime] is the device clock, never the server one.
typedef CommandContext = ({
  String commandId,
  DateTime dateTime,
  CommandSource source,
});
